### ISSUE TITLE
Settings menu mostly empty in latest Season of Discovery update

### ISSUE THREAD

**Issue by Ishar398** [RagedUnicorn/wow-classic-gearmenu#101]
The addon is still functional but it's not possible to add anything to Quickchange or change Gearbar configs because the settings window is empty.

**Comment by RagedUnicorn** [comment]
Hi @Ishar398 

This was indeed an issue that was caused by Blizzards latest patch. I built a workaround (3.4.10) for now and hopefully I can remove this later on when Blizzard fixes this.

https://github.com/Stanzilla/WoWUIBugs/issues/645

Cheers,
RagedUnicorn

**Comment by Ishar398** [comment]
Thanks, great addon I've used it for many years.
