### ISSUE TITLE
Can't change the gear bar from horizontal to vertical

### ISSUE THREAD

**Issue by Flobberz** [RagedUnicorn/wow-classic-gearmenu#11]
Is there a way to change the bar from horizontal to vertical? Also I was wondering if you could change the tooltip for the items to appear where all the other tooltips appear too. Thanks!

**Comment by RagedUnicorn** [comment]
Hi @Flobberz,

There is currently no way to have the slot appear in a vertical way but I put it on my todo list and might support that in a future version.

I agree with you about the tooltips (I was getting annoyed by this myself) and changed it to always appear wherever your other tooltips appear as well.

Cheers,
RagedUnicorn
