### ISSUE TITLE
Chat Spam

### ISSUE THREAD

**Issue by Starcheck** [RagedUnicorn/wow-classic-gearmenu#12]
Hey,

I really like the work done here!!
How can I get rid of teh status texts in the chat?

![image](https://user-images.githubusercontent.com/54445661/64695333-29a24d80-d49c-11e9-9cd5-200f762bd420.png)

**Comment by teh0mega** [comment]
@RagedUnicorn went over this in a different Issue-

> Not a problem. Make sure to do the following otherwise the debug messages will clutter your chat window.
> 
> This means however that interested people with some technical understanding can already download the master branch of the addon (name the folder GearMenu) and change some basic values in the `GM_Environment.lua` file (to stop the debug log spam).
> 
> Copy and overwrite the content of the file with the following:
> 
> ```lua
> RGGM_ENVIRONMENT = {
>   ADDON_IDENTIFIER = "com.ragedunicorn.wow.classic.gearmenu-addon",
>   LOG_LEVEL = 1,
>   LOG_EVENT = false,
>   DEBUG = false
> }
> ```

**Comment by RagedUnicorn** [comment]
Hi @Starcheck,

As teh0mega already wrote this is because there was no release version available. As of today however you can download the first release from here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases

Cheers,
RagedUnicorn
