### ISSUE TITLE
Weapon swap in combat

### ISSUE THREAD

**Issue by Starcheck** [RagedUnicorn/wow-classic-gearmenu#13]
Hi,

I noticed I cant swap my offhand weapon while being in combat. Manualy I can ofc swap weapons in combat but the add on is putting my offhand into que until I leave combat.

I couldnt find any option to disable this, or maybe I am just blind :D

Is there a work around to fix this?
Thanks you for the awesome work here!

**Comment by Starcheck** [comment]
Already reported here, didnt see.
https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/5

**Comment by Road-block** [comment]
Note that there is a bug (or at the very least very un-intuitive behavior) with Blizzard's own `AutoEquipCursorItem` used when you manually equip weapons by right clicking in your bags when it comes to off-hands (and shields).  

Going from 2H > 1H > OH/Shield will unequip the 1H that was replaced in the first step and you have to re-click it to finally get it to go in the mainhand slot.

The only workaround at the moment is to equip the OH/Shield first then the mainhand.
