### ISSUE TITLE
No Idea How To Use This Addon

### ISSUE THREAD

**Issue by webworthydesign** [RagedUnicorn/wow-classic-gearmenu#14]
All I see is a window that lets you click on items and pick other items that go in that slot. I don't see how to macro or keybind anything. The main page just has a bunch of TODOs for images (that will hopefully help with this). But I am totally lost. Is there somewhere I can go for a tutorial? I've tried googling and youtubing it but nothing. Sorry for posting this here, but I didn't know how else to get in touch with you.

Thanks!

**Comment by RagedUnicorn** [comment]
Hi @webworthydesign,

The todos where there because the addon was (and is) still under development. As of today you can find quite a lot of gifs that explain the most important features of the addon.

Cheers,
RagedUnicorn
