### ISSUE TITLE
Request: Option to fade gear menu untill mouse over

### ISSUE THREAD

**Issue by JohnEU** [RagedUnicorn/wow-classic-gearmenu#15]
Hi,

I am a big fan of the faded opacity in Dominos, that fades the bars untill mouse over. Since I would be using Gear Menu much like a normal bar, it would be great to have this option.

**Comment by RagedUnicorn** [comment]
Hi @JohnEU,

Sounds like something that is doable as an option. Can you give me a bit more info? Is there an example somewhere how this would look like?

Cheers,
RagedUnicorn

**Comment by JohnEU** [comment]
Yes, [https://github.com/tullamods/Dominos](https://github.com/tullamods/Dominos)

On the feature list: Fading bars. You can set your bars to fade out to a certain opacity when not moused over.

I think it should be implemented under: [https://github.com/tullamods/Dominos/blob/master/Dominos/core/fadeManager.lua](https://github.com/tullamods/Dominos/blob/master/Dominos/core/fadeManager.lua)

**Comment by RagedUnicorn** [comment]
Hi @JohnEU,

I investigated this a little bit more and unfortunately decided that I will not implement this.

The main reason is that all those buttons you see have to be SecureActionButtons and thus cannot be "touched" while in combat. This brings all sorts of strange situations. An example would be that a fadein during combat doesn't work and the same with fadeout. I don't think that I could implement this in a useful way.

Cheers,
RagedUnicorn

**Comment by JohnEU** [comment]
Hi @RagedUnicorn ,

Thanks for checking into this. Too bad that it is complicated to implement ;/

Thanks for a great addon.
