### ISSUE TITLE
Cannot Bind the Slots

### ISSUE THREAD

**Issue by phendrome** [RagedUnicorn/wow-classic-gearmenu#16]
The keybinding settings does not show up anywhere. 

Checked the following:
- Key Bindings > AddOns
- Interface Options > GearMenu

Using the latest release 1.0.

**Comment by RagedUnicorn** [comment]
Hi @phendrome,

Thanks for the report. There was indeed an issue with packaging the release. `Bindings.xml` was missing in the release and thus you where not getting the option to set your keybinds.

This is fixed now in df1cf2ef08fc02f55a3206a9ac28eeaca45ad91b and a new release v1.0.1 was just release.

Cheers,
RagedUnicorn
