### ISSUE TITLE
Trinket option suggestion

### ISSUE THREAD

**Issue by Ethugd** [RagedUnicorn/wow-classic-gearmenu#19]
hey man love the addon,

would it be possible to add an option so that the trinket selection window for trinkets becomes combined and u can left click to equip trinket 1 and right click to equip trinket 2?

similar addons have this functionality and its something ive been missing.

ALSO

is there a maximum of 10 trinkets displayed? i have way more than that and would like to have them all displayed :(

**Comment by RagedUnicorn** [comment]
Hi @Ethugd,

This sound like a great idea. I will try this out and if it works well I will add it. I would probably also add the same for rings.

About the maximum for 10 trinkets see - https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/22 This is indeed the case currently but I will increase it for the next release

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Cleanup - Closing this (was implemented in v2.1.1)
