### ISSUE TITLE
suggestion: ability to change gloves/boots/trinket when mounting and dismounting

### ISSUE THREAD

**Issue by Ethugd** [RagedUnicorn/wow-classic-gearmenu#21]
I love the quickchange menu, it makes my life really easy. was wondering if its possible to add some option to that menu that allows to set gloves/boots/trinket when u mount up and dismount.

**Comment by RagedUnicorn** [comment]
Hi @Ethugd,

While I like the idea I don't think that feature is something that belongs into GearMenu. This is a better fit for addons such as outfitter that lets you create itemsets. I will keep it in mind but I don't think that I will add this as a feature.

Cheers,
RagedUnicorn
