### ISSUE TITLE
Hide chat GearMenu lines

### ISSUE THREAD

**Issue by Leiludallas** [RagedUnicorn/wow-classic-gearmenu#23]
Hi,
Would you mind adding a way to hide all the chat flood please ? Thank you,

**Comment by novam4a1** [comment]
Yes please please, the chat flood is pretty intense.

**Comment by RagedUnicorn** [comment]
Hi @Leiludallas and @novam4a1 
Make sure to read the Readme instructions and download an actual release from here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases/tag/v1.0.1 instead of the development one.

Cheers,
RagedUnicorn
