### ISSUE TITLE
hide chat logging

### ISSUE THREAD

**Issue by amanalar** [RagedUnicorn/wow-classic-gearmenu#25]
great addon, just a question on how to hide the ticker messages that showup in main chat window. 

gearmenu core : bagupdate
gearmenu core : unit spellcast succeeded
gearmenu core : started changemenuticker
gearmenu core : stopped changemenuticker

and i guess the same for pulse.

**Comment by RagedUnicorn** [comment]
Hi @amanalar,

By reading the Readme instructions and downloading an actual release from here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases instead of the development one.

Cheers,
RagedUnicorn
