### ISSUE TITLE
Trigger keybind on key down rather than key up

### ISSUE THREAD

**Issue by jakeswork** [RagedUnicorn/wow-classic-gearmenu#26]
In my current set up I have my abilities triggered on key down, which is made possible via addons such as [Advanced Interface Options](https://www.curseforge.com/wow/addons/advancedinterfaceoptions) and [Classic Snowfall](https://github.com/Linae-Kronos/Classic-Snowfall).

I'd love if, when these options were enabled, it affected the responsiveness of the keybindings on this addon, too

Hard to properly show, but [here's an example of me holding down an action bar keybind, and then holding down the gear menu keybind](https://gyazo.com/82fc3e5cab71e740ed8fd3031f802422).

Perhaps the easiest approach is to just add this same functionality to the addon options (cast on keydown vs keyup)

**Comment by RagedUnicorn** [comment]
Hi @jakeswork,

I agree. Good idea! I did as you suggested and added this functionality into the addon itself. It is not dependent on any other addon. The functionality can be activated in the general options setting and is deactivated by default.

Commit is here: 880dd83fa2807e2dff4f5f3aba7eaf47f6cb71a5

The change itself will be included in the next release.

Cheers,
RagedUnicorn

**Comment by jakeswork** [comment]
Awesome. Great work :+1:
