### ISSUE TITLE
Add option to turn off the SPAM

### ISSUE THREAD

**Issue by electricmessiah** [RagedUnicorn/wow-classic-gearmenu#31]
This is the worst addon I have in regards to spam. It's constantly filling up the chat with what what appear to useless info or left behind debug comments. Please remove all of this or give an option to disable it.

**Comment by RagedUnicorn** [comment]
Hi @electricmessiah 

Make sure to read the Readme instructions and download an actual release from here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases/tag/v1.0.1 instead of the development one.

Cheers,
RagedUnicorn
