### ISSUE TITLE
Tidal Charm Issue

### ISSUE THREAD

**Issue by gamestuff** [RagedUnicorn/wow-classic-gearmenu#32]
Having a strange issue with [Tidal Charm](https://classic.wowhead.com/item=1404/tidal-charm).  For some reason at times it is showing as "Runecloth".  Tooltip/I'm assuming it's trying to use this item when I click on it. I can fix it by switching the items in my bag. so that the trinket is placed in the bag slot where the Runecloth was.    

This is the only trinket it's done this with so far.  Otherwise had zero problems, it's an amazingly useful addon.

**Comment by RagedUnicorn** [comment]
Hi @gamestuff 

This seems very similar to this issue https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/27

Are you using Bagnon by any chance? Did you try if the issue persists even with all other addons deactivated?

Cheers,
RagedUnciron

**Comment by gamestuff** [comment]
Yeah, it's Bagnon then.  I'll deactivate it and try but I'm almost positive it is the same issue.  It's just the same two items that constantly get switched in my case as well.

**Comment by RagedUnicorn** [comment]
What is suspicious once again the ids of the items are somewhat similar

https://classic.wowhead.com/item=1404/tidal-charm
https://classic.wowhead.com/item=14047/runecloth

Might need to create an issue for bagnon at one point but not quite sure what I could do about the issue on my side.

**Comment by gamestuff** [comment]
Sorry I might have jumped the gun, I am going to check further once I clean out my addons folder a bit.  I disabled bagnon and reloaded the UI and the issue persisted.  Will shortly try it again deactivating all addons and restarting the game.

**Comment by gamestuff** [comment]
Disabled all addons, restarted the game, enabled gearmenu, reloaded UI.  Still showing as Runecloth.  Restarted the game once and it is the same.  It shows the image for the trinket when I first mouseover the bar, but on mousing over the item it shows the tooltip for Runecloth.

**Comment by gamestuff** [comment]
New to github, and wasn't sure if I should triple post or edit posts to give you an indication.  But I think my last edit/discovery should maybe point to the issue.  Can delete this comment, just wanted to make sure edits don't get overlooked somehow, and unsure of etiquette.

**Comment by RagedUnicorn** [comment]
Not a problem. Just one more question. I'm trying to figure out whether its just a display issue for the tooltip or something else. Are you still able to use the tidal charm when it is equipt in the slot (by clicking or using a shortcut)?

**Comment by gamestuff** [comment]
Yes, when it is equipped I can use it.  The issue is not just tooltip though.  When I have the trinket unequipped, and it is further down it the bags than the Runecloth, it tries to equip the Runecloth instead and will not let me equip the trinket.   When the trinket is higher up in the bags than the Runecloth I can equip it normally.

**Comment by RagedUnicorn** [comment]
Ah I actually was just able to reproduce the issue with the winterfall firewater from the other ticket (had to move it in the first bag). Will investigate this. Thanks for all the effort already. Especially the placement in the bags helped I already have a suspicion what the issue might be.

**Comment by gamestuff** [comment]
Of course, glad I could help.  Good luck and appreciate the work on this.
