### ISSUE TITLE
Issue with getting error messages / notifications from addon

### ISSUE THREAD

**Issue by Mattyklol** [RagedUnicorn/wow-classic-gearmenu#33]
Hello! I love your addon but when I'm using it I'm getting spammed with notifications in my chat box. It all seems like non important stuff too, I will post a screenshot. Any way to disable messages from the addon?

**Comment by Mattyklol** [comment]
https://imgur.com/i47jSMu

https://imgur.com/KxrU7UO

**Comment by RagedUnicorn** [comment]
Hi @Mattyklol,

Make sure to read the Readme instructions and download an actual release from here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases/tag/v1.0.1 instead of the development one.

Congrats on the blade btw :)

Cheers,
RagedUnicorn
