### ISSUE TITLE
New look on bars (ugly with larger inset!)

### ISSUE THREAD

**Issue by JohnEU** [RagedUnicorn/wow-classic-gearmenu#34]
Hi, with 1.10 there is a larger (inset?) border on the bars. How do we switch back to the old amount?

Before 1.10
![image](https://user-images.githubusercontent.com/55697857/68619913-a8335f80-04cc-11ea-8da7-a99665bd184a.png)

After 1.10
![image](https://user-images.githubusercontent.com/55697857/68619989-d87afe00-04cc-11ea-8d84-c5f93d0e2b7e.png)

Update: It looks like the width of the black border does not scale with the scaling option in settings. Here is the max size icons with same bar width
![image](https://user-images.githubusercontent.com/55697857/68620216-517a5580-04cd-11ea-8783-d54f1d819208.png)

**Comment by RagedUnicorn** [comment]
Hi @JohnEU 

It does look indeed like I forgot about the black border when I implemented the button scaling. Thanks for the detailed description and the helpful screenshots. I will fix this with the next update.

Cheers,
RagedUnicorn
