### ISSUE TITLE
Swap OH in combat

### ISSUE THREAD

**Issue by JohnEU** [RagedUnicorn/wow-classic-gearmenu#35]
Hi,

I realise there was an issue raised before with swapping weapons in combat. I basically only have gearmenu shown in my UI and use that to swap gear. Therefore swapping OH in combat is crucial. Is there any way to modify the addon to allow swapping weapon/OH on click in combat?

**Comment by RagedUnicorn** [comment]
Hi @JohnEU 

Unfortunately without a change to the api by blizzard it is not.

See https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/5

Believe me I'm frustrated about that and would very much like that feature myself. I'm playing around a bit with some improvements that could help but essentially it all comes down to "You need to know what weapon you want to switch to before entering combat"

I was thinking about adding an extra slot below all gearslots that contain a weapon. You could then define a weapon for that slot which you want to switch to when clicking on it. This is however just a fancy description for creating a "weaponswitch-macro". Those work without a problem.

Addons can create such macros for you but only out of combat. E.g. as an example the popular addon "Spy" is creating targeting-macros for players that are near you but only while you're not in combat.

Cheers,
RagedUnicorn

**Comment by keugnu** [comment]
@RagedUnicorn does this also apply to wands? I have to use a normal action bar to switch wands in combat right now. I wish I could just use grrm.

**Comment by RagedUnicorn** [comment]
Cleanup - Closing this
