### ISSUE TITLE
Engineering trinkets missing!

### ISSUE THREAD

**Issue by featherbird** [RagedUnicorn/wow-classic-gearmenu#37]
Hey!

Love the addon, just seems like all the engineering trinkets aren't showing on the menu (Only the Ultrasafe Transporter one)! Also having trouble with Green Lens, it will only show the last used version ( e.g Shadow Wrath). 

One last thing, could it be possible to add a option to fade the menu? Would love to reduce the opacity or have a mouseover option! 

Thank you for the lovely addon!

**Comment by RagedUnicorn** [comment]
Hi @featherbird 

Thanks for the warm words :)

I suspect you need to change the filtering for the items to have your enginerring items show up. I'm using engineering myself and it seems to work fine for me. Some items for engineering are however of low "quality" (white text) and thus you need to change the itemfilter.

Here is an example:

https://github.com/RagedUnicorn/wow-classic-gearmenu#filter-items-by-quality

Do I understand this correctly with the Green Lens. You have multiple Green Lens items in your bag but it will only show one of them? I think I can investigate this a bit but I guess I already know why only one is showing up. Gearmenu filters the items in your bag for duplicates and thus only shows the first Green Lens that is found. All others have the same itemid as the first one and are filtered out. I will check if that can be improved. Maybe I could allow duplicate items in the changemenu with an addon option. This might also help people that have duplicates of items with a pvp and a pve enchant on them.

About the fading of the menu. I took some time at one point and investigated this a bit. The problem with this is mainly that all those gearslots where you put an item in are securebuttons. This means that I'm very limited to what I can do to the buttons while the player is in combat (e.g. fading out). Based on that I put it quite far on my backlog and I'm not sure if I will ever implement that feature.

Regards,
RagedUnicorn
