### ISSUE TITLE
Add ammo slot 

### ISSUE THREAD

**Issue by Clausi** [RagedUnicorn/wow-classic-gearmenu#38]
Playing a hunter sometimes needs you to change ammo. Can you integrate the slot into Gearmenu?

Afaik the ammo slot has the ID 0 https://wowwiki.fandom.com/wiki/InventorySlotId

**Comment by RagedUnicorn** [comment]
Hi @Clausi 

I guess that should be possible. I put it on my todo list :)

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Hi @Clausi 

Support for the ammoslot was implemented here - https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/00b4ad1f31f9b894b28f7e79b2571637665cd257

This will be included in the next version(v1.3.0)

Cheers,
RagedUnicorn
