### ISSUE TITLE
Can't figure out how to make equipment set + macro

### ISSUE THREAD

**Issue by ssateneth** [RagedUnicorn/wow-classic-gearmenu#4]
All I really need is something to make an equipment set and set it to a macro, including equipment set that makes me naked / no gear. I can't see to figure out how to do it with your addon. All it is is a horizontal bar for every gear slot.

I used to use Outfitter back in the day, and there exists no compatible version anymore since retail put in their own equipment manager.

**Comment by RagedUnicorn** [comment]
Hi @ssateneth,

This addon has a complete different purpose. It is not similar to outfitter. Its goal is to help with switching between single items (usually during combat). Please read the documentation and have a look at the example in the old vanilla version here - https://github.com/RagedUnicorn/wow-vanilla-gearmenu for some visual examples.

Cheers,
RagedUnicorn
