### ISSUE TITLE
Ability to ignore/hide specific items

### ISSUE THREAD

**Issue by padmanek** [RagedUnicorn/wow-classic-gearmenu#41]
Feature request: Ability to ignore/hide chosen items.
Simple thing like for example holding alt and right clicking to hide an item.
And then if you wont to unhide it just hold alt before mousing over so all items show up.

**Comment by padmanek** [comment]
Any response on this?

**Comment by RagedUnicorn** [comment]
Hi @padmanek 

I will consider this but not with a high priority because I think with filtering the item quality you should already be able to filter out "garbage" items and the interface effort to build this feature seems quite big to me.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Cleanup - Closing this
