### ISSUE TITLE
Second button item column is closing too fast

### ISSUE THREAD

**Issue by Zauxst** [RagedUnicorn/wow-classic-gearmenu#42]
When I want to swap gear which is found on the second column, the item columns closes instantly if I pass a quarter of the button size.

I've tried to outline the place where moving the mouse will not close the columns, if I move outside of the red zone the item will close.
![Untitled](https://user-images.githubusercontent.com/6393530/71498009-4ef87300-2863-11ea-9552-c016571553fb.jpg)

I have also increased the button size to maximum, if that counts to anything to help debug.

**Comment by Zauxst** [comment]
I want to add that in this morning I do not have this problem. Probably after a restart the 2nd column resized correctly and it was not resized at max.

**Comment by RagedUnicorn** [comment]
Hi @Zauxst 

Thanks for the report. I can confirm this issue. The changemenu is currently not properly recalculated when changing the slotsize. A relog or reload (/reload) of the interface fixes the issue.

I will fix this and include it in the next release.

Cheers
RagedUnicorn
