### ISSUE TITLE
tryna edit the code to have shirts

### ISSUE THREAD

**Issue by Brokentrojan** [RagedUnicorn/wow-classic-gearmenu#46]
Support for shirts? Macro conditional /equip [worn:shirt] is op as fuck, but i can't seem to successfuly edit the code to include shits sofar.

**Comment by Brokentrojan** [comment]
["name"] = "slot_name_feet",
    ["type"] = {"INVTYPE_FEET", "INVTYPE_BODY"},
    ["textureId"] = 136513,
    ["slotId"] = INVSLOT_FEET



Add INVTYPE_BODY as shown

**Comment by RagedUnicorn** [comment]
Hi @Brokentrojan 

I think it should definitely be possible to add the shirt as a slot. Out of curiosity why would anyone need that? :D

You can reopen the ticket if you want and I will see if we can add that slot with next release.

Cheers,
RagedUnicorn
