### ISSUE TITLE
pop up a lot of opration information

### ISSUE THREAD

**Issue by mcaww** [RagedUnicorn/wow-classic-gearmenu#47]
Whenever I perform a mouse operation, whether it is a player, NPC or device, the operation information will pop up in the chat window, which will seriously affect the chat with others, and I cannot find any settable location in the settings. Can it be modified?

**Comment by RagedUnicorn** [comment]
Hi @mcaww 

Really not sure if I understand your problem. Are you talking about something similar to https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/29? 

If so I would recommend that you either download the addon directly from Twitch/Curse (https://www.curseforge.com/wow/addons/gearmenu) or get an actual release from Github (https://github.com/RagedUnicorn/wow-classic-gearmenu/releases)

Cheers,
RagedUnicorn
