### ISSUE TITLE
macro interacte with gearmenu

### ISSUE THREAD

**Issue by 965611270** [RagedUnicorn/wow-classic-gearmenu#48]
Hi 

Is that possible for macro to callback gearmenu funciton? for example, I'd love to binding CombatQueue into my script instead using mouseclick。

**Comment by RagedUnicorn** [comment]
Hi @965611270 

That is certainly something that would be possible. Can you maybe elaborate a little bit on what your use case would be? I currently can only guess that you would want the functionality of adding a certain item from withing the macro into the CombatQueue?

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Hi @965611270 

A first basic implementation for this was added to the addon. It is not yet included in a release but you can see in the readme file what can be done.

See https://github.com/RagedUnicorn/wow-classic-gearmenu#macro-support

If you have another idea what should be possible with this please let me know.

Cheers,
RagedUnicorn
