### ISSUE TITLE
Any possible compatibility with Masque?

### ISSUE THREAD

**Issue by dreamscape89** [RagedUnicorn/wow-classic-gearmenu#50]
People love to crate a theme for their UI, masque skins the buttons for addons like Bartender and Dominis, would be nice if it would work with this addon as well to get everything in line.

https://www.curseforge.com/wow/addons/masque

**Comment by alexzaworski** [comment]
+1, being able to skin buttons as well as scale/space them would be a boon.

**Comment by phendrome** [comment]
Very good idea. Solves the issue of having different skin options.

**Comment by s1othfu1** [comment]
+1

**Comment by phendrome** [comment]
Digging the 1.3 update. Thanks for that @RagedUnicorn. What's the plan going further? Having Masque support or a more Blizz-like skin would be awesome. If you need any help let me know.

**Comment by ollema** [comment]
+1

**Comment by RagedUnicorn** [comment]
Cleanup - Closing this

See https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/39#issuecomment-998092148 for an update regarding skins/theme
