### ISSUE TITLE
Option to have popup grow downwards

### ISSUE THREAD

**Issue by Olorun** [RagedUnicorn/wow-classic-gearmenu#53]
While mousing over the gearmenu bar, it would be nice to have an option that the gear options move downward from the bar instead of upward.

**Comment by tehuno** [comment]
Yeah I would also like to be able to arrange the buttons more.  Like Maybe make two columns or allow you to split them apart, etc.

**Comment by RagedUnicorn** [comment]
Hi Guys,

I agree with you that I need to change something here. I was already playing a bit around with having much more flexibility of how the "GearBar" is setup. Think a player can create
multiple of those bars with as many slots as he wants. Thus allowing for setups such as having the trinkets in another place than other items.

This is however a big change to the addon and will take me a while to implement. I did however already start working on it.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Cleanup - Closing this (partially implemented with multiple gearBars)
