### ISSUE TITLE
Cooldown timer?

### ISSUE THREAD

**Issue by padmanek** [RagedUnicorn/wow-classic-gearmenu#57]
Is it possible to have a numeric CD instead of the swipe animation? Or even on top of the swipe animation?

**Comment by Olorun** [comment]
If you have OmniCC, you will see a numeric CD for everything.

**Comment by padmanek** [comment]
> If you have OmniCC, you will see a numeric CD for everything.

It will also add another set of numbers on all the actiobars, buffs, debuffs and all the weakauras which already have their own timers. I've tried it and then everything gets "double" timers. It's not a solution.

**Comment by Olorun** [comment]
(you can disable all of those and let OmniCC handle it) Yeah I guess you're right

**Comment by RagedUnicorn** [comment]
Hi @padmanek 

Initially I developed the whole handling of the timer by myself but I later decided to rely on what is already there by the blizzard interface. It should also work with addons that modify actionbuttons. By default however its just using this swipe animation.

Regards,
RagedUnicorn
