### ISSUE TITLE
A problem from hunters.

### ISSUE THREAD

**Issue by zellfy** [RagedUnicorn/wow-classic-gearmenu#58]
Thank you for your amazing work.
I'm a hunter, I found gearmenu can't change the trinket after I cast Feign Death and get out of battle immediately. But when I get up it works at once. Actually if I change it with click the item in my bag when I am casting Feign Death, the trinket can be changed.
So is there something can optimalize？

**Comment by RagedUnicorn** [comment]
Hi @zellfy 

Can you tell me if you this is the same issue as https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/54? And are you ussing the newest version of GearMenu?

Regards,
Michael

**Comment by zellfy** [comment]
OK，I have tried the newest version and the problem was all done. Thank you for your work.
