### ISSUE TITLE
Spam in the chat and cant save gearset

### ISSUE THREAD

**Issue by Daviid666** [RagedUnicorn/wow-classic-gearmenu#6]
Everytime i mouse over anything it spams the chat with something. I cant disable that.
Also, i cant save my healing gear and my dps gear for quick swap.

**Comment by RagedUnicorn** [comment]
Hi @Daviid666,

About the chat spam please see what I wrote here - https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/3

I'm not sure if I understand any of the other points you mentionend but it seems like your mixing up what the intention of the addon is. This is not an addon to manage gearsets unlike other addons like outfitter. It has a whole different purpose which you should be able to read up on in the readme file.

Also the the vanilla version for some visual images of the features (I will add those to this repository as well at some point).

https://github.com/RagedUnicorn/wow-vanilla-gearmenu/blob/master/README.md

Cheers,
RagedUnicorn
