### ISSUE TITLE
Not seeing certain trinkets on the popup-list

### ISSUE THREAD

**Issue by Hhomle** [RagedUnicorn/wow-classic-gearmenu#60]
Title says it all; specifically i cannot see net-o-matic or mortar trinkets in the pop-up menu on the bar. Rest of the trinkets work just fine, and I am able to manually equip both trinkets and use then normally with hotkeys. Anyone else had any issues like this?

Awesome addon other than that btw!

**Comment by RagedUnicorn** [comment]
See https://github.com/RagedUnicorn/wow-classic-gearmenu/issues/37

**Comment by Hhomle** [comment]
ah of course, awesome thank you!
