### ISSUE TITLE
Suggestion - Unequipping Items

### ISSUE THREAD

**Issue by HolteUnderscore** [RagedUnicorn/wow-classic-gearmenu#61]
Is it possible to add an "empty slot" to the popup "menu" for each slot which would put the item in your bags please?

**Comment by RagedUnicorn** [comment]
Hi @HolteUnderscore 

This feature was implemented with v1.4.0. Make sure to check in the general options to enable it and let me know what you think about it.

Reference:
https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/c576ece68522a9f990e8c0fe38902e013e564e85
https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/588d962ef747349de689d22fa346a34123194715

Cheers,
RagedUnicorn
