### ISSUE TITLE
Quickchange Cloak 

### ISSUE THREAD

**Issue by Jinnai** [RagedUnicorn/wow-classic-gearmenu#66]
Cloak is missing in the Quickchange menu

**Comment by RagedUnicorn** [comment]
Hi @Jinnai 

Thanks for the hint this was indeed a bug on how I determined whether a certain slots was already in the dropdownmenu or not. I used the the texture id of said slot. I found out however that some of the slots have the same textureId and thus would not show up in the menu. I use a separate unique id know and this fixes that issue.

Cheers,
RagedUnicorn
