### ISSUE TITLE
Macro Bridge does not work with all item slots

### ISSUE THREAD

**Issue by rparliment** [RagedUnicorn/wow-classic-gearmenu#68]
I am getting lua errors attempting to run this macro

`#showtooltip Goblin Rocket Boots
/run GM_AddToCombatQueue(7189,8)`

I cannot seem to get the macros to work for anything other then trinkets.

**Comment by RagedUnicorn** [comment]
Hi @rparliment 

Couldn't try this with the goblin rocket boots but did so with the gnomish ones and this worked for me.

```
#showtooltip Goblin Rocket Boots
/run GM_AddToCombatQueue(10724,8)
```

Not sure if you're macro is actually on one line or if this is just a formatting issue here in the ticket?

Cheers,
RagedUnicorn
