### ISSUE TITLE
Bar style similar to Blizzard UI

### ISSUE THREAD

**Issue by ujellyx** [RagedUnicorn/wow-classic-gearmenu#7]
Would it be possible to make the bar style similar to the Blizzard default action bars? With the spacing and the border/blank-icon-textures?

**Comment by phendrome** [comment]
I'm pretty certain that it's coming. The 1.12.1 version had that.

**Comment by RagedUnicorn** [comment]
Hi @ujellyx,

Sorry to disappoint the current style is what I'm going for. There might be some visual changes in the future of course but I don't aim to replicate the blizzard default action bars. It is of course possible todo what you asked for and everyone is free to get a copy of the addon and adapt it to whatever style he prefers.

Cheers,
RagedUnicorn

**Comment by phendrome** [comment]
Is it a hard task to change to the bars so they look like the Blizzard default bars? I'd look into it if I get a direction how to approach it.

**Comment by RagedUnicorn** [comment]
I think it shouldn't be that much of work. You could essentialy copy and paste a lot from the vanilla version - https://github.com/RagedUnicorn/wow-vanilla-gearmenu. I think it would be quite a bit of work of supporting different style for the addon itself such as themes. Thats the main reason why I don't really like adding this. Also I'm working on other addons that will use a similar style.

Cheers,
RagedUnicorn

**Comment by phendrome** [comment]
Hmpf. That's a shame, as many people really do prefer to keep the style as close to Blizzard as possible. If you don't add it, I'll probably do it myself. :)

I mean, supporting only your style and Blizzard would be more than enough. I don't think people would want anything else with a ton of theming.
