### ISSUE TITLE
Move and Dock Items/Trinket menus

### ISSUE THREAD

**Issue by Xiverz** [RagedUnicorn/wow-classic-gearmenu#71]
Hi man, I've been using this addon for a while now. I have preferred it over others because of its extra features like queuing swaps and activation on keypress down. 

However, I really wish specifically that the trinket menu could be permanently left open on the screen and moved/resized to a better position, it would help a lot in pvp situations where you have to constantly switch your trinkets up on the fly.

If its too much work its fine, don't worry about it haha :P

Thanks for making a great addon anyway!

**Comment by RagedUnicorn** [comment]
Hi @Xiverz 

Certainly something that could be implemented. I saw other addons that do this. I think if I would implement this it would be a "separate menu" that can be dragged somewhere on the screen and would just show all trinkets that the user has in his bags.

I think I would need to define something like - left click equips trinket into slot x and right click equips trinket into slot y.

What do you think about this? Is that what you mean?

Cheers,
RagedUnicorn

**Comment by Xiverz** [comment]
@RagedUnicorn 

Yes that's perfect, it's exactly what I mean! 

Just like the old addon TrinketMenu which has been abandoned, but with extra features and without the bugs :D

**Comment by RagedUnicorn** [comment]
Implemented with v2.1.2
