### ISSUE TITLE
Alternate combined equipping behavior

### ISSUE THREAD

**Issue by bonermobile** [RagedUnicorn/wow-classic-gearmenu#73]
First of all, great addon, much better than TrinketMenu or ItemRack when it comes to swapping individual items. Looks nicer too.

Secondly, I'd like to request an option for an absolute style of combined equipping. One where left click always selects the top or first slot of a pair and right click always selects the bottom or second slot, regardless of which slot was initially moused over. Basically a functionality similar to what you proposed in #71.

**Comment by RagedUnicorn** [comment]
Hi @bonermobile 

I'm a bit unsure what really is the best way of implementing combined equipping. Some people seem to support your view others want a different implementation. It is not even that big of an effort to change it but I want to avoid changing this all the time.

Maybe we can get some people in here describing exactly what they expect in the form of:

If I left-click on the upper slot I want it to do x
If I right-click on the upper slot I want it to do y

If I left-click on the lower slot I want it to do x
If I right-click on the lower slot I want it to do y

The current behavior as implemented is the following:
If I left-click on the upper slot it will equip the chosen item in the clicked slot
If I right-click on the upper slot it will equip the chosen item in the lower slot

If left-click on the lower slot it will equip the chosen item in the clicked slot
If I right-click on the lower slot it will equip the chosen item in the upper slot

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Something similar was implemented with the feature TrinketMenu. Closing this.
