### ISSUE TITLE
Druid Idols in inventory do not show up as swappable in gear menu

### ISSUE THREAD

**Issue by ConnorJBeck** [RagedUnicorn/wow-classic-gearmenu#74]
I've added one of my gearmenu slots as type "Ranged", and it shows my currently equipped idol. However, hovering over it, it doesn't show any of the idols in my inventory. I can't find a better slot name than Ranged (though as a druid the slot is referred to as "Relic"). I cannot confirm whether this behaviour is also occurring for shaman or paladin relics.

**Comment by RagedUnicorn** [comment]
Hi @ConnorJBeck,

Thanks for bringing this up. This was indeed a bug. GearMenu did not support relics at all. I do not have a character with a relic myself. So I'm unable to test it myself but it is such an easy fix that I just included it and it will be in the next release.

Once the release is out (1-2 days) please let me know if it works for you.

Cheers,
RagedUnicorn

**Comment by ConnorJBeck** [comment]
Thanks! I'll keep an eye out and let you know if it's fixed.

**Comment by RagedUnicorn** [comment]
@ConnorJBeck Just a ping v1.5.0 is out

**Comment by ConnorJBeck** [comment]
Just checked and it works like a charm. Thanks!
