### ISSUE TITLE
Allow posY to be less than 0

### ISSUE THREAD

**Issue by padkipz** [RagedUnicorn/wow-classic-gearmenu#75]
Really love the addon, finding it far superior to ItemRack/TrinketMenu, the only thing I'd love to be able to do is align it to the bottom of my screen.

If you take a look at the attached screenshots, I have dragged the frame as far down as it will go, but I believe the frame dragging border is stopping it from being dragged lower. I've tried setting ["posY"] = -10+ but this doesn't seem to have any effect in-game, as if the frame simply can't go lower than 0.
![WowClassic_2020-10-02_13-17-57](https://user-images.githubusercontent.com/3637452/94922255-ca9de500-04b1-11eb-8cd0-eb599d4ce696.png)
![WowClassic_2020-10-02_13-17-34](https://user-images.githubusercontent.com/3637452/94922267-d12c5c80-04b1-11eb-99cb-48ce0757ce88.png)

**Comment by RagedUnicorn** [comment]
Hi @padkipz 

I see your issue and fixed it. I will include it in the next release which I'm about to release.

Cheers,
RagedUnicorn
