### ISSUE TITLE
TBC update

### ISSUE THREAD

**Issue by padkipz** [RagedUnicorn/wow-classic-gearmenu#78]
Are there any plans for a TBC update? Appreciate we're still in early stages of beta, but current error is:

> Message: Interface\AddOns\GearMenu\gui/GM_GearBar.lua:59: attempt to call method 'SetBackdrop' (a nil value)
> Time: Mon Apr 12 12:47:07 2021
> Count: 1
> Stack: Interface\AddOns\GearMenu\gui/GM_GearBar.lua:59: attempt to call method 'SetBackdrop' (a nil value)
> [string "@Interface\AddOns\GearMenu\gui/GM_GearBar.lua"]:59: in function `BuildGearBar'
> [string "@Interface\AddOns\GearMenu\code/GM_Core.lua"]:180: in function `Initialize'
> [string "@Interface\AddOns\GearMenu\code/GM_Core.lua"]:101: in function `OnEvent'
> [string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>
> 
> Locals: gearBarFrame = GM_GearBar {
>  0 = <userdata>
> }
> gearBarSlotSize = 40
> (*temporary) = nil
> (*temporary) = GM_GearBar {
>  0 = <userdata>
> }
> (*temporary) = <table> {
>  bgFile = "Interface\DialogFrame\UI-DialogBox-Background"
> }
> (*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
> mod = <table> {
>  gearBar = <table> {
>  }
>  combatQueue = <table> {
>  }
>  itemManager = <table> {
>  }
>  addonConfiguration = <table> {
>  }
>  gearManager = <table> {
>  }
>  gearSlotMenu = <table> {
>  }
>  cmd = <table> {
>  }
>  generalMenu = <table> {
>  }
>  target = <table> {
>  }
>  L = <table> {
>  }
>  common = <table> {
>  }
>  uiHelper = <table> {
>  }
>  logger = <table> {
>  }
>  aboutContent = <table> {
>  }
>  RegisterEvents = <function> defined @Interface\AddOns\GearMenu\code/GM_Core.lua:61
>  ShowWelcomeMessage = <function> defined @Interface\AddOns\GearMenu\code/GM_Core.lua:203
>  macro = <table> {
>  }
>  tooltip = <table> {
>  }
>  changeMenu = <table> {
>  }
>  OnEvent = <function> defined @Interface\AddOns\GearMenu\code/GM_Core.lua:98
>  configuration = <table> {
>  }
>  quickChange = <table> {
>  }
>  OnLoad = <function> defined @Interface\AddOns\GearMenu\code/GM_Core.lua:52
>  Initialize = <function> defined @Interface\AddOns\GearMenu\code/GM_Core.lua:171
>  filter = <table> {
>  }
>  quickChangeMenu = <table> {
>  }
>  ticker = <table> {
>  }
>  tag = "Core"
> }
> me = <table> {
>  GearSlotOnEnter = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:574
>  StartDragFrame = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:457
>  SetKeyBindingFont = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:218
>  ShowCooldowns = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:673
>  HideCooldowns = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:664
>  SetupDragFrame = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:447
>  UpdateGearBarTextures = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:318
>  CreateGearSlot = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:90
>  CreateCombatQueueSlot = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:164
>  UpdateSpellRange = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:242
>  GearSlotOnDragStart = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:630
>  GearSlotOnLeave = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:592
>  ShowKeyBindings = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:646
>  UpdateClickHandler = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:529
>  GearSlotOnReceiveDrag = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:602
>  HideKeyBindings = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:655
>  StopDragFrame = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:468
>  GearSlotOnClick = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:545
>  UpdateCombatQueue = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:421
>  SetupEvents = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:492
>  UpdateTexture = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:402
>  UpdateGearBar = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:272
>  UpdateGearSlotCooldown = <function> defined @Interface\AddOns\GearMenu\gui/GM_GearBar.lua:375
>  UpdateKeyBindings = <function> defined @Interface\AddOns\GearMenu\

Thanks for all your work on this during classic!

**Comment by RagedUnicorn** [comment]
Hi @padkipz 

You're welcome. I didn't play much classic lately but will definitely be back with TBC and thus I can say that yes GearMenu will support TBC (I want it myself :)).

Sadly I don't have access to the beta myself but the issue above I already saw and should be an easy fix. Overall I don't expect a lot of work for it to work on tbc. I might start working on the update in a couple days. If there are people that read this, have access to the beta and are willing to support me please let me know. Then I might be able to add first versions to this ticket to try out.

Cheers,
RagedUnicorn

**Comment by padkipz** [comment]
Thanks for the quick response!

I have access to the beta myself and am more than willing to help out if I can.

**Comment by ap0yuv** [comment]
seems to be super easy.

changed files:

GM_GearBar.lua

```
 91:      local gearSlot = CreateFrame(
 92:        "Button",
 93:        RGGM_CONSTANTS.ELEMENT_GEAR_BAR_SLOT .. position,
 94:        gearBarFrame,
 95:        "SecureActionButtonTemplate" and "BackdropTemplateMixin" and "BackdropTemplate"
  )

```


GM_UiHelper.lua

` 97:      local highlightFrame = CreateFrame("FRAME", nil, slot, "BackdropTemplateMixin" and "BackdropTemplate")`

GM_ChangeMenu.lua

` 51:     changeMenuFrame = CreateFrame("Frame", RGGM_CONSTANTS.ELEMENT_GEAR_BAR_CHANGE_FRAME, gearBarFrame, "BackdropTemplateMixin" and "BackdropTemplate")`
`102:      local changeSlot = CreateFrame("Button", RGGM_CONSTANTS.ELEMENT_GEAR_BAR_SLOT .. position, frame, "BackdropTemplateMixin" and "BackdropTemplate")`

i don't know how curseforge works here and u prolly need to declare someting to new to have a tbc version of the addon...

**Comment by RagedUnicorn** [comment]
Hi guys,

Sorry about the silence worked a lot on the 2.0.0 release for gearmenu.

I also put some thought in how I want to continue development for gearmenu with burning crusade classic coming out. I decided to have this in a separate repository because I think the addon will diverge more and more from the classic version with time passing and I don't want to have `if classic else` blocks all over the place.

You can find the bcc repository here if you're interested - https://github.com/RagedUnicorn/wow-bcc-gearmenu

For all the people that are not interested in the code this should be fully transparent. The project will be the same on curseforge. There will be a new version showing up with the supprted version 2.5.1(tbc). An example for that you can see here https://www.curseforge.com/wow/addons/pulse/files

I also found some additional issues besides the obvious BackdropTemplate change and fixed those. I currently have a fully working version commited to the new wow-bcc-gearmenu repository (no release yet) and doing last tests on the ptr server. Meaning you should expect to have a version ready for the prepatch.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Closing this. The version is available and seems to be working.

Cheers,
RagedUnicorn
