### ISSUE TITLE
"Window"-size stays the same, even with disabled slots.

### ISSUE THREAD

**Issue by ujellyx** [RagedUnicorn/wow-classic-gearmenu#8]
When I disable certain slots, the slots themselves are hidden, but the size of the gearmenu-bar (in width) stays the same - preventing clicks through the hidden space.

**Comment by RagedUnicorn** [comment]
Hi @ujellyx,

This was indeed an issue and is fixed in https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/83817349702f31a0c468ff1745d26f3dd719139e. Thanks for reporting this.

Cheers,
RagedUnicorn
