### ISSUE TITLE
Changeslot size is slightly bigger than Gearslot size when set to the same size

### ISSUE THREAD

**Issue by padkipz** [RagedUnicorn/wow-classic-gearmenu#80]
With the latest update, my changeslot size is a tad bigger than the gearslot size when they're set to the same size.

See attached for an example - I have both set to 26, but the changeslotsize is more like 30/31.
![image](https://user-images.githubusercontent.com/3637452/118363112-b6af7b00-b58a-11eb-8131-15183fbb8474.png)

**Comment by RagedUnicorn** [comment]
Hi Thanks for your report

Looks like you are right about that I can see the issue myself.

Especially with the biggest size it can be seen
![frames](https://user-images.githubusercontent.com/26184132/118400534-5db31600-b662-11eb-959e-c3ef8f67df79.png)

Fixed look
![fixed](https://user-images.githubusercontent.com/26184132/118400563-702d4f80-b662-11eb-9823-2a1b51e512ac.png)

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Fixed and will be included in the next release

Notes to myself:
* Always SetPoint when creating a frame initially
* This fix needs to be applied to the bcc version

Again thanks for your report 👍
