### ISSUE TITLE
Unable to bind mouse buttons to slots after the 2.0 update

### ISSUE THREAD

**Issue by rgalan89** [RagedUnicorn/wow-classic-gearmenu#81]
Hello

After the 2.0 update im unable to bind the mouse4 or mouse5 buttons to any slot, even i tried to delete and create a new GearBar configuration but still doesnt recognize the bind.

**Comment by RagedUnicorn** [comment]
Hi @rgalan89 

Thanks for your report I can confirm that I can reproduce this. Looks like binding mouse buttons works a bit different from other buttons and I need to implement this additional behavior.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Fixed and will be included in the next release. Had to change quite a bit to support mousebuttons but the following should now work

`BUTTON3, BUTTON4, BUTTON5, MOUSEWHEELUP, MOUSEWHEELDOWN`

Note for myself:
* This change needs to be applied to the bcc version
