### ISSUE TITLE
Border size (unsure if issue, or feature request)

### ISSUE THREAD

**Issue by padkipz** [RagedUnicorn/wow-classic-gearmenu#82]
In previous versions of GMM, the border size around the Gearslot and Changeslot was bigger/bolder, see image:
![image](https://user-images.githubusercontent.com/3637452/118624766-57877b80-b7c1-11eb-99f4-75a0c46e431b.png)

Now, the border size is a lot smaller - I'm pretty sure the border itself it still there, just doesn't mimic what I had previously. I honstly can't remember if this was a setting, or if it possibly had Masque support(?), but you can see in this image the difference:
![image](https://user-images.githubusercontent.com/3637452/118624959-8271cf80-b7c1-11eb-918b-fcb359fc1017.png)

Is it possible to add an option to increase border size, or add (re-add?) Masque support?

**Comment by RagedUnicorn** [comment]
Hi @padkipz 

I think it is an issue. I changed this by accident with the last bugfix. I will fix this with the next release but I think having a setting to change that border is a bit over the top. I want to keep the configuration simple whenever possible.

Cheers,
RagedUnicorn
