### ISSUE TITLE
Equip previous item

### ISSUE THREAD

**Issue by trying-to-function** [RagedUnicorn/wow-classic-gearmenu#84]
Would be great if you could set an item (for example [Rocket Boots Xtreme](https://tbc.wowhead.com/item=23824/rocket-boots-xtreme)) to equip the item that was equipped prior to the rocket boots. Hopefully #70 in mind as well.

**Comment by RagedUnicorn** [comment]
Hi @trying-to-function 

I think this would complicate the quickChange process a lot. I understand that it might be a bit tedious to have quite a lot of quickChange rules but my experience so far showed me that people usually have an engineering item that they want to switch back to their "main" item after using the engineering one.

Based on that I don't plan to implement this. Thanks for the suggestion though.

Cheers
RagedUnicorn
