### ISSUE TITLE
Equip same item after X time

### ISSUE THREAD

**Issue by trying-to-function** [RagedUnicorn/wow-classic-gearmenu#85]
Would like to be able to set the following:

Set [Nigh Invulnerability Belt](https://tbc.wowhead.com/spell=30570/nigh-invulnerability-belt) to swap to an item without an on-use such as [General's Leather Belt](https://tbc.wowhead.com/item=28423/generals-leather-belt) then after 5 minutes swap back to [Nigh Invulnerability Belt](https://tbc.wowhead.com/spell=30570/nigh-invulnerability-belt).

**Comment by RagedUnicorn** [comment]
Not a bad idea for sure but I need to disappoint. I won't be able to invest to much time into addon development and I think the feature would require a lot of ui work. I think this would be much easier with a macro.
