### ISSUE TITLE
Cancel item swaps if manually changed

### ISSUE THREAD

**Issue by trying-to-function** [RagedUnicorn/wow-classic-gearmenu#86]
I use [Bloodlust Brooch](https://tbc.wowhead.com/item=29383/bloodlust-brooch) with a 20 second timer to swap into [Slayer's Crest](https://tbc.wowhead.com/item=23041/slayers-crest) during trash. But sometimes I need to manually swap to [Mark of the Champion](https://tbc.wowhead.com/item=23207/mark-of-the-champion). Currently I have to wait the 20 seconds before swapping trinkets otherwise Slayers will be equipped.

**Comment by RagedUnicorn** [comment]
Hi @trying-to-function 

I can see how this can be an issue but this was an intentional design choice with QuickChange. The item is only placed into the combatQueue when it is actually time to switch. This of course doesn't give you the option to cancel it then.

Cheers,
RagedUnicorn
