### ISSUE TITLE
Vertical Orientation

### ISSUE THREAD

**Issue by kaminador** [RagedUnicorn/wow-classic-gearmenu#90]
Hi, I love Gearmenu and have been using it for years. I am currently reworking my UI and am wondering if it is possible to put Gearmenu in a vertical orientation aka 1 column instead of 1 row. Hopefully I'm not overlooking something simple in the options ><. Thanks in advance!

**Comment by Slivo-fr** [comment]
Same question here, it's the only thing really missing coming from the old TrinketMenu

**Comment by RagedUnicorn** [comment]
Not planned for now sorry
