### ISSUE TITLE
Host Upon alternative Providers like WoWUpHub

### ISSUE THREAD

**Issue by ap0yuv** [RagedUnicorn/wow-classic-gearmenu#92]
Due CurseForge/Overwolf shutting down the API for alternative Addonmangers , GearMenu cannot bei updated anymore with the WoWUp-Client.

Could a alternative Package/Release be supllied so WoWUp can pull from GitHub ?

**Comment by RagedUnicorn** [comment]
Hi @ap0yuv 

I will look into it. According to WoWUp I already do what they suggest but not sure if it actually works.

`Politely lobby the author of your missing addons to host them somewhere else, such as Wago or GitHub.`

All releases are currently placed into GitHub releases additionally to the curseforge upload.

https://github.com/RagedUnicorn/wow-classic-gearmenu/releases

**Comment by ap0yuv** [comment]
from what i got so far is they want you to add another file `release.json` which they need to make it work.

Read about it **[here](https://github.com/WowUp/WowUp/issues/1245#issuecomment-1128360257)**

**Comment by ap0yuv** [comment]
Format seems to be something like this:

```json
{"releases":[{"filename":"WowUp-1.0.9.zip","nolib":false,"metadata":[{"flavor":"classic","interface":11402},{"flavor":"mainline","interface":90200},{"flavor":"bcc","interface":20504}]}]}
```

**Comment by RagedUnicorn** [comment]
Hi @ap0yuv 

I made all my addons available on Wago.io (e.g. https://addons.wago.io/addons/gearmenu). This enables them to work again with the WoWUp client.

Cheers,
Ragedunicorn
