### ISSUE TITLE
black square in the middle

### ISSUE THREAD

**Issue by Kasaki95** [RagedUnicorn/wow-classic-gearmenu#93]
Gearmenu is causing a black square in the middle of screen since Ulduar update Wednesday the 18th in WoW classic WotLK

![Gearmenu](https://user-images.githubusercontent.com/122985521/213175358-2221d1b5-42fd-4dc6-b058-e75b471d7046.png)

**Comment by ap0yuv** [comment]
Bliizard changed to api 10 from 9 with the patch which makes alot of "optional" parameters mandatory and also error handling changed from "be silent" to "throw error" on a few functions.
also certain UI function got renamed in v10 e.g. C_Container.PickupContainerItem instead of PickupContainerItem.

**Comment by ap0yuv** [comment]
GM_GearBar.lua:154+
```old
local iconHolderTexture = combatQueueSlot:CreateTexture(
    RGGM_CONSTANTS.ELEMENT_GEAR_BAR_SLOT_ICON_TEXTURE_NAME,
    "LOW",
    nil
  )
```

```changed
local iconHolderTexture = combatQueueSlot:CreateTexture(
    RGGM_CONSTANTS.ELEMENT_GEAR_BAR_SLOT_ICON_TEXTURE_NAME,
    "BACKGROUND",
    nil
  )
```

**Comment by ap0yuv** [comment]
GM_Cooldown.lua:86 has to be:

`local startTime, duration = C_Container.GetItemCooldown(itemId)`

**Comment by RagedUnicorn** [comment]
Hi @ap0yuv 

I'm aware of the update and the issues. Honestly I did not plan do to a wotlk update of the addon at all. I'm no longer playing WoW for a long time and was expecting that at some point Blizzard would break the addon :). I will however investigate and see what I can do/what the effort would be and let you know in this ticket what I will do or not do (no promises).

I made a list of all errors that I could find yesterday and the solution to it. I quickly put those together. I will attach that version to this issue. If you want to help you could test a bit with this version and let me know if you can find other issues.
[GearMenu.zip](https://github.com/RagedUnicorn/wow-classic-gearmenu/files/10447126/GearMenu.zip)

Message: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
Time: Tue Jan 17 21:39:48 2023
Count: 1
Stack: bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBar.lua"]:154: in function `CreateCombatQueueSlot'
[string "@Interface/AddOns/GearMenu/gui/GM_ThemeCustom.lua"]:92: in function <Interface/AddOns/GearMenu/gui/GM_ThemeCustom.lua:49>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/GearMenu/gui/GM_GearBar.lua"]:108: in function `CreateGearSlots'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBar.lua"]:89: in function `BuildGearBar'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBar.lua"]:59: in function `BuildGearBars'
[string "@Interface/AddOns/GearMenu/code/GM_Core.lua"]:230: in function `Initialize'
[string "@Interface/AddOns/GearMenu/code/GM_Core.lua"]:107: in function `OnEvent'
[string "*GM_Frame.xml:8_OnEvent"]:1: in function <[string "*GM_Frame.xml:8_OnEvent"]:1>

Locals: (*temporary) = "bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))"


Use an actual layer value no longer allowed to use unknown values I guess?
https://wowpedia.fandom.com/wiki/Layer



---

Message: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:83: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Tue Jan 17 21:54:01 2023
Count: 1
Stack: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:83: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:83: in function `GetItemsForInventoryType'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:103: in function `UpdateChangeMenu'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBar.lua"]:689: in function <Interface/AddOns/GearMenu/gui/GM_GearBar.lua:688>

Locals: inventoryType = <table> {
 1 = "INVTYPE_HEAD"
}
idx = 1
items = <table> {
}
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"
mod = <table> {
 gearBar = <table> {
 }
 gearBarConfigurationMenu = <table> {
 }
 addonConfiguration = <table> {
 }
 configuration = <table> {
 }
 cmd = <table> {
 }
 gearBarChangeMenu = <table> {
 }
 target = <table> {
 }
 aboutContent = <table> {
 }
 gearBarManager = <table> {
 }
 common = <table> {
 }
 macro = <table> {
 }
 tooltip = <table> {
 }
 Initialize = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:219
 quickChangeMenu = <table> {
 }
 themeClassic = <table> {
 }
 combatQueue = <table> {
 }
 itemManager = <table> {
 }
 keyBind = <table> {
 }
 gearManager = <table> {
 }
 libUIDropDownMenuTemplates = <table> {
 }
 themeCustom = <table> {
 }
 L = <table> {
 }
 OnLoad = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:52
 uiHelper = <table> {
 }
 logger = <table> {
 }
 generalMenu = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:61
 ShowWelcomeMessage = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:256
 gearBarConfigurationSubMenu = <table> {
 }
 themeCoordinator = <table> {
 }
 gearBarStorage = <table> {
 }
 OnEvent = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:100
 quickChange = <table> {
 }
 ticker = <table> {
 }
 libUiDropDownMenu = <table> {
 }
 filter = <table> {
 }
 trinketMenu = <table> {
 }
 trinketConfigurationMenu = <table> {
 }
 cooldown = <table> {
 }
 tag = "Core"
}
me = <table> {
 FindItemInBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:252
 GetItemsForInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:73
 FindEquipedItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:230
 AddItemsMatchingInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:364
 FindQuickChangeItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:272
 IsDuplicateItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:319
 EquipItemById = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:140
 UnequipItemToBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:393
 HasItemEquipedInSlot = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:419
 SwitchItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:179
 tag = "ItemManager"
}


This looks like it was moved to https://wowpedia.fandom.com/wiki/API_GetItemCooldown

---

Message: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:83: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Tue Jan 17 21:56:38 2023
Count: 1
Stack: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:83: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:83: in function `GetItemsForInventoryType'
[string "@Interface/AddOns/GearMenu/gui/GM_TrinketMenu.lua"]:111: in function `UpdateTrinketMenuResize'
[string "@Interface/AddOns/GearMenu/gui/GM_TrinketMenu.lua"]:76: in function `BuildTrinketMenu'
[string "@Interface/AddOns/GearMenu/code/GM_Core.lua"]:238: in function `Initialize'
[string "@Interface/AddOns/GearMenu/code/GM_Core.lua"]:107: in function `OnEvent'
[string "*GM_Frame.xml:8_OnEvent"]:1: in function <[string "*GM_Frame.xml:8_OnEvent"]:1>

Locals: inventoryType = <table> {
 1 = "INVTYPE_TRINKET"
}
idx = 1
items = <table> {
}
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "attempt to call global 'GetContainerNumSlots' (a nil value)"
mod = <table> {
 gearBar = <table> {
 }
 gearBarConfigurationMenu = <table> {
 }
 addonConfiguration = <table> {
 }
 configuration = <table> {
 }
 cmd = <table> {
 }
 gearBarChangeMenu = <table> {
 }
 target = <table> {
 }
 aboutContent = <table> {
 }
 gearBarManager = <table> {
 }
 common = <table> {
 }
 macro = <table> {
 }
 tooltip = <table> {
 }
 Initialize = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:219
 quickChangeMenu = <table> {
 }
 themeClassic = <table> {
 }
 combatQueue = <table> {
 }
 itemManager = <table> {
 }
 keyBind = <table> {
 }
 gearManager = <table> {
 }
 libUIDropDownMenuTemplates = <table> {
 }
 themeCustom = <table> {
 }
 L = <table> {
 }
 OnLoad = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:52
 uiHelper = <table> {
 }
 logger = <table> {
 }
 generalMenu = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:61
 ShowWelcomeMessage = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:256
 gearBarConfigurationSubMenu = <table> {
 }
 themeCoordinator = <table> {
 }
 gearBarStorage = <table> {
 }
 OnEvent = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:100
 quickChange = <table> {
 }
 ticker = <table> {
 }
 libUiDropDownMenu = <table> {
 }
 filter = <table> {
 }
 trinketMenu = <table> {
 }
 trinketConfigurationMenu = <table> {
 }
 cooldown = <table> {
 }
 tag = "Core"
}
me = <table> {
 FindItemInBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:252
 GetItemsForInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:73
 FindEquipedItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:230
 AddItemsMatchingInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:364
 FindQuickChangeItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:272
 IsDuplicateItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:319
 EquipItemById = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:140
 UnequipItemToBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:393
 HasItemEquipedInSlot = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:419
 SwitchItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:179
 tag = "ItemManager"
}


Moved to https://wowpedia.fandom.com/wiki/API_C_Container.GetContainerNumSlots

--

Message: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:84: attempt to call global 'GetContainerItemID' (a nil value)
Time: Tue Jan 17 21:58:15 2023
Count: 1
Stack: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:84: attempt to call global 'GetContainerItemID' (a nil value)
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:84: in function `GetItemsForInventoryType'
[string "@Interface/AddOns/GearMenu/gui/GM_TrinketMenu.lua"]:111: in function `UpdateTrinketMenuResize'
[string "@Interface/AddOns/GearMenu/gui/GM_TrinketMenu.lua"]:76: in function `BuildTrinketMenu'
[string "@Interface/AddOns/GearMenu/code/GM_Core.lua"]:238: in function `Initialize'
[string "@Interface/AddOns/GearMenu/code/GM_Core.lua"]:107: in function `OnEvent'
[string "*GM_Frame.xml:8_OnEvent"]:1: in function <[string "*GM_Frame.xml:8_OnEvent"]:1>

Locals: inventoryType = <table> {
 1 = "INVTYPE_TRINKET"
}
idx = 1
items = <table> {
}
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(for index) = 1
(for limit) = 20
(for step) = 1
j = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = "attempt to call global 'GetContainerItemID' (a nil value)"
mod = <table> {
 gearBar = <table> {
 }
 gearBarConfigurationMenu = <table> {
 }
 addonConfiguration = <table> {
 }
 configuration = <table> {
 }
 cmd = <table> {
 }
 gearBarChangeMenu = <table> {
 }
 target = <table> {
 }
 aboutContent = <table> {
 }
 gearBarManager = <table> {
 }
 common = <table> {
 }
 macro = <table> {
 }
 tooltip = <table> {
 }
 Initialize = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:219
 quickChangeMenu = <table> {
 }
 themeClassic = <table> {
 }
 combatQueue = <table> {
 }
 itemManager = <table> {
 }
 keyBind = <table> {
 }
 gearManager = <table> {
 }
 libUIDropDownMenuTemplates = <table> {
 }
 themeCustom = <table> {
 }
 L = <table> {
 }
 OnLoad = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:52
 uiHelper = <table> {
 }
 logger = <table> {
 }
 generalMenu = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:61
 ShowWelcomeMessage = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:256
 gearBarConfigurationSubMenu = <table> {
 }
 themeCoordinator = <table> {
 }
 gearBarStorage = <table> {
 }
 OnEvent = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:100
 quickChange = <table> {
 }
 ticker = <table> {
 }
 libUiDropDownMenu = <table> {
 }
 filter = <table> {
 }
 trinketMenu = <table> {
 }
 trinketConfigurationMenu = <table> {
 }
 cooldown = <table> {
 }
 tag = "Core"
}
me = <table> {
 FindItemInBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:252
 GetItemsForInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:73
 FindEquipedItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:230
 AddItemsMatchingInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:364
 FindQuickChangeItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:272
 IsDuplicateItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:319
 EquipItemById = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:140
 UnequipItemToBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:393
 HasItemEquipedInSlot = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:419
 SwitchItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:179
 tag = "ItemManager"
}


Moved to https://wowpedia.fandom.com/wiki/API_GetContainerItemID

---

Message: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:255: attempt to call global 'GetContainerItemLink' (a nil value)
Time: Tue Jan 17 21:59:50 2023
Count: 1
Stack: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:255: attempt to call global 'GetContainerItemLink' (a nil value)
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:255: in function `FindItemInBag'
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:181: in function `SwitchItems'
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:152: in function `EquipItemById'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:428: in function `ChangeSlotOnClick'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:402: in function <...terface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua:401>

Locals: itemId = 37390
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
(for index) = 1
(for limit) = 20
(for step) = 1
j = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = 0
(*temporary) = 1
(*temporary) = "attempt to call global 'GetContainerItemLink' (a nil value)"


Moved to https://wowpedia.fandom.com/wiki/API_GetContainerItemLink

---

Message: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:184: attempt to call global 'GetContainerItemInfo' (a nil value)
Time: Tue Jan 17 22:00:50 2023
Count: 1
Stack: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:184: attempt to call global 'GetContainerItemInfo' (a nil value)
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:184: in function `SwitchItems'
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:152: in function `EquipItemById'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:428: in function `ChangeSlotOnClick'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:402: in function <...terface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua:401>

Locals: itemId = 37390
slotId = 14
bagNumber = 1
bagPos = 5
(*temporary) = nil
(*temporary) = 1
(*temporary) = 5
(*temporary) = "attempt to call global 'GetContainerItemInfo' (a nil value)"
me = <table> {
 FindItemInBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:252
 GetItemsForInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:73
 FindEquipedItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:230
 AddItemsMatchingInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:364
 FindQuickChangeItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:272
 IsDuplicateItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:319
 EquipItemById = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:140
 UnequipItemToBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:393
 HasItemEquipedInSlot = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:419
 SwitchItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:179
 tag = "ItemManager"
}
mod = <table> {
 gearBar = <table> {
 }
 gearBarConfigurationMenu = <table> {
 }
 addonConfiguration = <table> {
 }
 configuration = <table> {
 }
 cmd = <table> {
 }
 gearBarChangeMenu = <table> {
 }
 target = <table> {
 }
 aboutContent = <table> {
 }
 gearBarManager = <table> {
 }
 common = <table> {
 }
 macro = <table> {
 }
 tooltip = <table> {
 }
 Initialize = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:219
 quickChangeMenu = <table> {
 }
 themeClassic = <table> {
 }
 combatQueue = <table> {
 }
 itemManager = <table> {
 }
 keyBind = <table> {
 }
 gearManager = <table> {
 }
 libUIDropDownMenuTemplates = <table> {
 }
 themeCustom = <table> {
 }
 L = <table> {
 }
 OnLoad = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:52
 uiHelper = <table> {
 }
 logger = <table> {
 }
 generalMenu = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:61
 ShowWelcomeMessage = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:256
 gearBarConfigurationSubMenu = <table> {
 }
 themeCoordinator = <table> {
 }
 gearBarStorage = <table> {
 }
 OnEvent = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:100
 quickChange = <table> {
 }
 ticker = <table> {
 }
 libUiDropDownMenu = <table> {
 }
 filter = <table> {
 }
 trinketMenu = <table> {
 }
 trinketConfigurationMenu = <table> {
 }
 cooldown = <table> {
 }
 tag = "Core"
}


Moved to https://wowpedia.fandom.com/wiki/API_GetContainerItemInfo

---

Message: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:188: attempt to call global 'PickupContainerItem' (a nil value)
Time: Tue Jan 17 22:01:59 2023
Count: 1
Stack: Interface/AddOns/GearMenu/code/GM_ItemManager.lua:188: attempt to call global 'PickupContainerItem' (a nil value)
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:188: in function `SwitchItems'
[string "@Interface/AddOns/GearMenu/code/GM_ItemManager.lua"]:152: in function `EquipItemById'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:428: in function `ChangeSlotOnClick'
[string "@Interface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua"]:402: in function <...terface/AddOns/GearMenu/gui/GM_GearBarChangeMenu.lua:401>

Locals: itemId = 37293
slotId = 1
bagNumber = 0
bagPos = 3
_ = <table> {
 hasLoot = false
 hyperlink = "[Mask of the Watcher]"
 iconFileID = 133084
 hasNoValue = false
 isLocked = false
 itemID = 37293
 isBound = true
 stackCount = 1
 isFiltered = false
 isReadable = false
 quality = 3
}
_ = nil
isLocked = nil
(*temporary) = nil
(*temporary) = 0
(*temporary) = 3
(*temporary) = "attempt to call global 'PickupContainerItem' (a nil value)"
me = <table> {
 FindItemInBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:252
 GetItemsForInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:73
 FindEquipedItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:230
 AddItemsMatchingInventoryType = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:364
 FindQuickChangeItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:272
 IsDuplicateItem = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:319
 EquipItemById = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:140
 UnequipItemToBag = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:393
 HasItemEquipedInSlot = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:419
 SwitchItems = <function> defined @Interface/AddOns/GearMenu/code/GM_ItemManager.lua:179
 tag = "ItemManager"
}
mod = <table> {
 gearBar = <table> {
 }
 gearBarConfigurationMenu = <table> {
 }
 addonConfiguration = <table> {
 }
 configuration = <table> {
 }
 cmd = <table> {
 }
 gearBarChangeMenu = <table> {
 }
 target = <table> {
 }
 aboutContent = <table> {
 }
 gearBarManager = <table> {
 }
 common = <table> {
 }
 macro = <table> {
 }
 tooltip = <table> {
 }
 Initialize = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:219
 quickChangeMenu = <table> {
 }
 themeClassic = <table> {
 }
 combatQueue = <table> {
 }
 itemManager = <table> {
 }
 keyBind = <table> {
 }
 gearManager = <table> {
 }
 libUIDropDownMenuTemplates = <table> {
 }
 themeCustom = <table> {
 }
 L = <table> {
 }
 OnLoad = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:52
 uiHelper = <table> {
 }
 logger = <table> {
 }
 generalMenu = <table> {
 }
 RegisterEvents = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:61
 ShowWelcomeMessage = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:256
 gearBarConfigurationSubMenu = <table> {
 }
 themeCoordinator = <table> {
 }
 gearBarStorage = <table> {
 }
 OnEvent = <function> defined @Interface/AddOns/GearMenu/code/GM_Core.lua:100
 quickChange = <table> {
 }
 ticker = <table> {
 }
 libUiDropDownMenu = <table> {
 }
 filter = <table> {
 }
 trinketMenu = <table> {
 }
 trinketConfigurationMenu = <table> {
 }
 cooldown = <table> {
 }
 tag = "Core"
}


Moved to https://wowpedia.fandom.com/wiki/API_PickupContainerItem

---

Need to use isCancelled function

https://wowpedia.fandom.com/wiki/API_C_Timer.NewTimer

**Comment by ap0yuv** [comment]
In GM_ItemManager.lua
Replaces:
GetContainerNumSlots => C_Container.GetContainerNumSlots
GetContainerItemID => C_Container.GetContainerItemID
GetContainerNumSlots => C_Container.GetContainerNumSlots
GetContainerItemLink => C_Container.GetContainerItemLink
GetContainerItemInfo => C_Container.GetContainerItemInfo
PickupContainerItem => C_Container.PickupContainerItem

In GM_GearBarChangeMenu.lua:321: 
GetItemCooldown => C_Container.GetItemCooldown

**Comment by ap0yuv** [comment]
Hello @RagedUnicorn , ty for replying that fast. I wasnt aware that you already started working on some of the issues , and only wanted to write down here yet what i found so far.
i am gonna take a look on what you have changed later and will see if i can spot more neccessary changes.

**Comment by ap0yuv** [comment]
oh my bad actually didnt see we actually talking in the wrong repo

**Comment by ap0yuv** [comment]
I am not good at this GitHub stuff hope it did that properly now.

@RagedUnicorn theres a PR: https://github.com/RagedUnicorn/wow-bcc-gearmenu/pull/9

**Comment by RagedUnicorn** [comment]
Went ahead and created a separate wotlkc version of the addon - https://github.com/RagedUnicorn/wow-wotlkc-gearmenu. Releases are out on curseforge and wago.io.

As mentioned I did not have a lot of time to test but integrated all issues mentioned by @ap0yuv and some more. Thanks for bringing this up and helping out - I appreciate it.

Cheers,
RagedUnicorn
